### POST request for login
POST {{host}}/auth/login
Content-Type: application/json
Accept: application/json
Set-Cookie: fn_boilerplate.session_token

{
  "email": "pj@gmail.com",
  "password": "Passw0rd"
}
